// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/factory/contact.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/factory/contact.go -destination=test/mock/factory/contact.go -package=factorymock
//

// Package factorymock is a generated GoMock package.
package factorymock

import (
	reflect "reflect"
	dto "stock-controll/internal/application/dto"
	entity "stock-controll/internal/domain/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockIContactFactory is a mock of IContactFactory interface.
type MockIContactFactory struct {
	ctrl     *gomock.Controller
	recorder *MockIContactFactoryMockRecorder
}

// MockIContactFactoryMockRecorder is the mock recorder for MockIContactFactory.
type MockIContactFactoryMockRecorder struct {
	mock *MockIContactFactory
}

// NewMockIContactFactory creates a new mock instance.
func NewMockIContactFactory(ctrl *gomock.Controller) *MockIContactFactory {
	mock := &MockIContactFactory{ctrl: ctrl}
	mock.recorder = &MockIContactFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContactFactory) EXPECT() *MockIContactFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIContactFactory) Create(arg0 dto.CreateContactDTO) (*entity.Contact, []error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(*entity.Contact)
	ret1, _ := ret[1].([]error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIContactFactoryMockRecorder) Create(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIContactFactory)(nil).Create), arg0)
}
